# Use balenalabs wifi-connect with rpi architecture (for RPi Zero/1)
# Supported archs: aarch64, armv7hf, amd64, rpi
# Source: https://github.com/balenablocks/wifi-connect
FROM bh.cr/balenalabs/wifi-connect-rpi

# Set custom portal SSID and passphrase
ENV PORTAL_SSID="DigitalClock Setup"
ENV PORTAL_PASSPHRASE="clocksetup"
